spring:
  application:
    name: eureka-consumer-ribbon
server:
  port: 2102
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/
