server:
  port: 7777
#  port: ${random.int[7070,7079]}
spring:
  application:
    name: spring-cloud-eureka-provider
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:D:/temp/h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  main:
#    allow-bean-definition-overriding: true # 支持bean名称覆盖，如果FeignClint 指定不同contextId可不设置该属性
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9002/eureka/, http://${eureka.instance.hostname}:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
#  Actuator Security 要求必须打开需要expose的endpoints，默认打开health and info
management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  enable: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  log:
    enabled: true
#  client:
#    name: ${spring.application.name}
#    url: ${eureka.instance.instance-id}
logging:
  level:
    com:
      gara: DEBUG


# check for updated list of servers every 10 seconds
spring-cloud-eureka-provider:
  ribbon:
    ServerListRefreshInterval: 10000

