server:
  port: 7777
#  port: ${random.int[7070,7079]}
spring:
  application:
    name: spring-cloud-eureka-provider
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
#  main:
#    allow-bean-definition-overriding: true # 支持bean名称覆盖，如果FeignClint 指定不同contextId可不设置该属性
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/,http://${eureka.instance.hostname}:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
#  Actuator Security 要求必须打开需要expose的endpoints，默认打开health and info
management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  enable: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  log:
    enabled: true
  client:
    name: spring-cloud-eureka-provider
    url: ${eureka.instance.instance-id}
logging:
  level:
    com:
      gara: DEBUG


# check for updated list of servers every 10 seconds
spring-cloud-eureka-provider:
  ribbon:
    ServerListRefreshInterval: 10000
