server:
  port: ${random.int[7070,7079]}

spring:
  application:
    name: spring-cloud-eureka-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/,http://${eureka.instance.hostname}:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
#  Actuator Security 要求必须打开需要expose的endpoints，默认打开health and info
management:
  endpoints:
    web:
      exposure:
        include: '*'
