server:
  port: 9999
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/GIT/SpringCloud
#          force-pull: true
          skip-ssl-validation: true
#          force-pull: true
          search-paths: /config-repo
#          skip-ssl-validation: true
management:
  endpoints:
    web:
      exposure:
        include: '*'