server:
  port: 9999
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GaraYing/config-repo
#          uri: https://github.com/spring-cloud-samples/config-repo
#          fo rce-pull: true
          skip-ssl-validation: true
# where application is injected as the spring.config.name in the SpringApplication (what is normally application in a regular Spring Boot app), profile is an active profile (or comma-separated list of properties),
# and label is an optional git label (defaults to master.)
#
#  config:
#    name: gara
#          force-pull: true
#          search-paths: /config-repo
#          skip-ssl-validation: true
management:
  endpoints:
    web:
      exposure:
        include: '*'