spring:
  application:
    name: eureka-consumer
#  cloud:
#    client:
#      ipAddress: 127.0.0.1
server:
  port: 2101
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/

