eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/,http://${eureka.instance.hostname}:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1
server:
  port: 3001
#  tomcat:
#    max-http-post-size:
spring:
  application:
    name: service-feign
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true
  main:
    allow-bean-definition-overriding: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

swagger:
  enable: true

feign:
  log:
    enabled: true
# print log
logging:
  level:
    com:
      gara: DEBUG